version: '3'
services:
  server:
    container_name: alovoa-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: alovoa
    environment:
      - vault.token
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    extra_hosts:
      - "mysql:172.17.0.1"

